name: to_do_list_task
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=3.0.0-393.0.dev <4.0.0'}
dependencies:
  flutter: {sdk: flutter}
  provider:
  fluttertoast:
  hive:
  hive_flutter:
  loading_animation_widget:
  shared_preferences:
  cupertino_icons:
dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints:
  build_runner:
  hive_generator:
flutter:
  uses-material-design: true
  assets: []
  fonts: []
