name: to_do_list_task
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=3.0.0-393.0.dev <4.0.0'}
dependencies:
  flutter: {sdk: flutter}
  provider: null
  fluttertoast: null
  shared_preferences: null
  cupertino_icons: null
dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets: []
  fonts: []
